### ISSUE TITLE
Function "Rank" is missing

### ISSUE THREAD

**Issue by RobWunderlich** [MattFryer/QlikView-Notepad-plus-plus#5]
No "Rank()" function in Qlikview.xml

**Comment by MattFryer** [comment]
Hi Rob, 
This is because rank is only valid in expressions and so far I've only included functions which are valid in QV script. I wasn't sure how much people Notepad++ for expressions
-Matt

**Comment by RobWunderlich** [comment]
I see. I was actually trying to abuse it as a comprehensive list of functions for another project.

**Comment by MattFryer** [comment]
I have a full list somewhere that I put together when I first created the language definitions. If I can find it I'll let you have it Rob.
