### ISSUE TITLE
Exit Scrip Keyword

### ISSUE THREAD

**Issue by shubhamsingh64** [MattFryer/QlikView-Notepad-plus-plus#7]
Exit Script keywords have been defined together. It doesn't show a suggestion for Script after writing Exit.
Also for below two statements:
 Exit Script;
 Exit Script ;
The first one is shown in black while second one is blue, the only difference between above is statements is a space between 't' and ';' .

**Comment by MattFryer** [comment]
This will be resolved in the soon to be release v2.5
